import rawSchema from "../../schema.json";

export type ColumnDefinition = {
  column: string;
  type: string;
  nullable: boolean;
  default: string | null;
};

export type ForeignKeyDefinition = {
  column: string;
  references_table: string;
  references_column: string;
};

export type TableDefinition = {
  table_name: string;
  primary_key: string[];
  columns: ColumnDefinition[];
  foreign_keys: ForeignKeyDefinition[];
};

export type PortalSection = {
  title: string;
  description: string;
  accent: string;
  tables: string[];
};

const schema = rawSchema as TableDefinition[];

export const portalSections: PortalSection[] = [
  {
    title: "Organization Setup",
    description: "Core structures, roles, locations, and service taxonomy.",
    accent: "#1A4F8A",
    tables: [
      "parent_entity",
      "sub_location",
      "department_master",
      "designation_master",
      "role_master",
      "service_type_master",
      "employee_category_master",
    ],
  },
  {
    title: "Employee Management",
    description: "Employee master data, lifecycle history, finance, and skills.",
    accent: "#2A7D5F",
    tables: [
      "employee_master",
      "employee_finance",
      "employee_bank_history",
      "employee_skills",
      "employee_shift_preference",
      "employee_transfer_history",
      "employee_salary_history",
      "employee_documents",
      "employee_audit_log",
    ],
  },
  {
    title: "Leave Management",
    description: "Holiday rules, leave policy, variants, and assignments.",
    accent: "#FF6600",
    tables: [
      "holiday_calendar",
      "leave_type_master",
      "leave_policy_master",
      "policy_variant",
      "policy_assignment",
    ],
  },
  {
    title: "Shift & Roster",
    description: "Planning, slotting, and versioned roster history.",
    accent: "#FFD700",
    tables: ["shift_policy_master", "roster", "roster_slots", "roster_history"],
  },
  {
    title: "Attendance & CO",
    description: "Daily attendance capture and compensatory-off ledger.",
    accent: "#1A4F8A",
    tables: ["attendance", "co_ledger"],
  },
  {
    title: "Payroll & Compliance",
    description: "Payroll structure, statutory slabs, runs, and compliance ledgers.",
    accent: "#2A7D5F",
    tables: [
      "salary_structure_master",
      "pt_slab_master",
      "minimum_wage_master",
      "state_compliance_master",
      "payroll_period_master",
      "payroll_components",
      "payroll_deductions",
      "payroll_run",
      "payroll_employee_summary",
      "payroll_compliance",
    ],
  },
  {
    title: "Exit & Settlement",
    description: "Separation workflows, gratuity, and full-and-final closure.",
    accent: "#FF6600",
    tables: ["employee_exit_workflow", "gratuity_tracking", "fnf_settlement"],
  },
  {
    title: "Location Operations",
    description: "Store operating hours, delivery zones, and onboarding readiness.",
    accent: "#1A4F8A",
    tables: [
      "location_operating_hours",
      "location_service_config",
      "delivery_zone",
      "location_onboarding_checklist",
    ],
  },
  {
    title: "Audit & System Logs",
    description: "Audit trails, module events, and realtime operational records.",
    accent: "#2A7D5F",
    tables: [
      "indipet_audit_log",
      "indipet_module_records",
      "indipet_realtime_events",
      "location_audit_log",
    ],
  },
];

export const allTables = schema;

export const tableLookup = Object.fromEntries(
  schema.map((table) => [table.table_name, table]),
) as Record<string, TableDefinition>;

export const allTableNames = schema.map((table) => table.table_name);

export function formatLabel(value: string) {
  return value
    .replace(/_/g, " ")
    .replace(/\b\w/g, (segment) => segment.toUpperCase())
    .trim();
}

export function formatTypeLabel(type: string) {
  return type
    .replace(/without time zone/g, "")
    .replace(/character varying/g, "text")
    .replace(/double precision/g, "decimal")
    .replace(/\s+/g, " ")
    .trim();
}

export function getFieldKind(column: ColumnDefinition) {
  const type = column.type.toLowerCase();

  if (type.includes("bool")) return "checkbox";
  if (type.includes("json")) return "json";
  if (type.includes("timestamp")) return "datetime";
  if (type === "date") return "date";
  if (type === "time") return "time";
  if (type.includes("numeric") || type.includes("integer") || type.includes("double") || type.includes("real")) {
    return "number";
  }

  return "text";
}

export function getPrimaryKey(table: TableDefinition) {
  return table.primary_key[0] ?? null;
}

export function isAutoGenerated(column: ColumnDefinition) {
  return Boolean(column.default && column.default.includes("nextval("));
}

export function shouldShowInCreateForm(column: ColumnDefinition, tableName?: string) {
  if (tableName === "sub_location" && column.column === "location_code") {
    return false;
  }

  if (tableName === "service_type_master" && column.column === "linked_department_code") {
    return false;
  }

  if (tableName === "department_master" && ["department_code", "revenue_centre_code"].includes(column.column)) {
    return false;
  }

  return !(column.default && isAutoGenerated(column));
}

export function getTableDisplayColumn(table: TableDefinition, row: Record<string, unknown>) {
  // Combine first+last name for person records
  if (row["first_name"] !== undefined && row["first_name"] !== null) {
    const parts = [row["first_name"], row["last_name"]].filter(Boolean).map(String).join(" ").trim();
    if (parts) return parts;
  }

  const preferredColumns = [
    `${table.table_name.replace(/_master$/, "")}_name`,
    "name",
    "title",
    "legal_name",
    "leave_name",
    "period_code",
    "roster_code",
    "code",
    "employee_name",
    "location_name",
    "department_name",
    "designation_name",
    "policy_name",
    "variant_name",
    "role_name",
  ];

  for (const column of preferredColumns) {
    if (row[column] !== undefined && row[column] !== null && String(row[column]).trim() !== "") {
      return String(row[column]);
    }
  }

  const primaryKey = getPrimaryKey(table);
  if (primaryKey && row[primaryKey] !== undefined && row[primaryKey] !== null) {
    return String(row[primaryKey]);
  }

  const firstTextColumn = table.columns.find((column) => {
    const kind = getFieldKind(column);
    return kind === "text" && row[column.column] !== undefined && row[column.column] !== null;
  });

  if (firstTextColumn) {
    return String(row[firstTextColumn.column]);
  }

  return table.table_name;
}

export function countVisibleFields(table: TableDefinition) {
  return table.columns.filter((column) => shouldShowInCreateForm(column, table.table_name)).length;
}
