import { pool, quoteIdentifier } from "@/lib/db";
import {
  allTables,
  formatLabel,
  getFieldKind,
  getPrimaryKey,
  formatEmployeeCode,
  isAutoGenerated,
  tableLookup,
  type ColumnDefinition,
  type TableDefinition,
} from "@/lib/portal-schema";

export type RecordPayload = Record<string, unknown>;

export type HolidayChartFilter = {
  calendarYear?: number | null;
  stateCode?: string | null;
  locationId?: string | null;
};

function getTable(tableName: string): TableDefinition {
  const table = tableLookup[tableName];
  if (!table) {
    throw new Error(`Unknown table: ${tableName}`);
  }

  return table;
}

function normalizeValue(column: ColumnDefinition, value: unknown) {
  if (value === undefined) {
    return undefined;
  }

  if (value === null || value === "") {
    return null;
  }

  const kind = getFieldKind(column);

  if (kind === "checkbox") {
    if (typeof value === "boolean") return value;
    if (typeof value === "string") return ["true", "1", "on", "yes"].includes(value.toLowerCase());
    return Boolean(value);
  }

  if (kind === "number") {
    if (typeof value === "number") return value;
    const parsed = Number(value);
    return Number.isNaN(parsed) ? null : parsed;
  }

  if (kind === "json") {
    if (typeof value === "string") {
      try {
        return JSON.parse(value);
      } catch {
        return null;
      }
    }
    return value;
  }

  if (kind === "date" || kind === "time" || kind === "datetime") {
    return String(value);
  }

  return String(value);
}

function normalizeRecordInput(table: TableDefinition, input: RecordPayload) {
  const normalized: Record<string, unknown> = {};

  for (const column of table.columns) {
    if (!(column.column in input)) continue;
    const value = normalizeValue(column, input[column.column]);
    if (value !== undefined) {
      normalized[column.column] = value;
    }
  }

  return normalized;
}

function getOrderColumn(table: TableDefinition) {
  return getPrimaryKey(table) ?? table.columns[0]?.column ?? "";
}

function decorateEmployeeCode(table: TableDefinition, row: Record<string, unknown>) {
  if (table.table_name !== "employee_master") {
    return row;
  }

  return {
    ...row,
    employee_code: formatEmployeeCode(row),
  };
}

function buildWhereClause(table: TableDefinition, recordId: string, paramOffset = 0) {
  const primaryKey = getPrimaryKey(table);
  if (!primaryKey) {
    throw new Error(`Table ${table.table_name} does not have a primary key`);
  }

  const pkColumn = table.columns.find((column) => column.column === primaryKey);
  const value = normalizeValue(pkColumn ?? table.columns[0], recordId);

  return {
    where: `${quoteIdentifier(primaryKey)} = $${paramOffset + 1}`,
    values: [value],
  };
}

function getInboundForeignKeys(tableName: string) {
  return allTables.flatMap((table) =>
    table.foreign_keys
      .filter((foreignKey) => foreignKey.references_table === tableName)
      .map((foreignKey) => ({ table, foreignKey })),
  );
}

type Queryable = { query: typeof pool.query };

async function resetTableSequence(client: Queryable, tableName: string) {
  const table = getTable(tableName);
  const primaryKey = getPrimaryKey(table);

  if (!primaryKey) {
    return;
  }

  const pkColumn = table.columns.find((column) => column.column === primaryKey);
  if (!pkColumn || !isAutoGenerated(pkColumn)) {
    return;
  }

  const sequenceResult = await client.query<{ sequence_name: string | null }>(
    "select pg_get_serial_sequence($1, $2) as sequence_name",
    [table.table_name, primaryKey],
  );

  const sequenceName = sequenceResult.rows[0]?.sequence_name;
  if (!sequenceName) {
    return;
  }

  await client.query(
    `select setval($1, coalesce((select max(${quoteIdentifier(primaryKey)}) from ${quoteIdentifier(table.table_name)}), 0) + 1, false)`,
    [sequenceName],
  );
}

// Holiday chart resolver removed — use generic table rows via listTableRows

async function deleteTableRowWithDependents(
  client: Queryable,
  tableName: string,
  recordId: string,
  visited: Set<string>,
  touchedTables: Set<string>,
) {
  const table = getTable(tableName);
  const primaryKey = getPrimaryKey(table);

  if (!primaryKey) {
    throw new Error(`Table ${table.table_name} does not have a primary key`);
  }

  const pkColumn = table.columns.find((column) => column.column === primaryKey);
  const recordValue = normalizeValue(pkColumn ?? table.columns[0], recordId);
  const visitKey = `${table.table_name}:${String(recordValue)}`;

  if (visited.has(visitKey)) {
    return null;
  }

  const currentResult = await client.query(
    `select * from ${quoteIdentifier(table.table_name)} where ${quoteIdentifier(primaryKey)} = $1 limit 1`,
    [recordValue],
  );

  const currentRow = currentResult.rows[0];
  if (!currentRow) {
    return null;
  }

  visited.add(visitKey);
  touchedTables.add(table.table_name);

  for (const { table: childTable, foreignKey } of getInboundForeignKeys(table.table_name)) {
    const childPrimaryKey = getPrimaryKey(childTable);
    if (!childPrimaryKey) {
      continue;
    }

    const referencedValue = currentRow[foreignKey.references_column];
    if (referencedValue === undefined || referencedValue === null || referencedValue === "") {
      continue;
    }

    const childRows = await client.query(
      `select ${quoteIdentifier(childPrimaryKey)} as primary_key from ${quoteIdentifier(childTable.table_name)} where ${quoteIdentifier(foreignKey.column)} = $1`,
      [referencedValue],
    );

    for (const childRow of childRows.rows) {
      await deleteTableRowWithDependents(client, childTable.table_name, String(childRow.primary_key), visited, touchedTables);
    }
  }

  const deleteResult = await client.query(
    `delete from ${quoteIdentifier(table.table_name)} where ${quoteIdentifier(primaryKey)} = $1 returning *`,
    [recordValue],
  );

  return deleteResult.rows[0] ?? currentRow;
}

export async function listTableRows(tableName: string, limit = 25, offset = 0) {
  const table = getTable(tableName);
  const orderColumn = getOrderColumn(table);
  const rowsResult = await pool.query(
    `select * from ${quoteIdentifier(table.table_name)} order by ${quoteIdentifier(orderColumn)} desc limit $1 offset $2`,
    [limit, offset],
  );
  const countResult = await pool.query(`select count(*)::int as count from ${quoteIdentifier(table.table_name)}`);

  return {
    table,
    rows: rowsResult.rows.map((row) => decorateEmployeeCode(table, row)),
    total: Number(countResult.rows[0]?.count ?? 0),
  };
}

export async function listSubLocationRowsByParentEntity(parentEntityId: string, limit = 25, offset = 0) {
  const table = getTable("sub_location");
  const orderColumn = getOrderColumn(table);
  const rowsResult = await pool.query(
    `select * from ${quoteIdentifier(table.table_name)} where ${quoteIdentifier("parent_entity_id")} = $1 order by ${quoteIdentifier(orderColumn)} desc limit $2 offset $3`,
    [parentEntityId, limit, offset],
  );
  const countResult = await pool.query(
    `select count(*)::int as count from ${quoteIdentifier(table.table_name)} where ${quoteIdentifier("parent_entity_id")} = $1`,
    [parentEntityId],
  );

  return {
    table,
    rows: rowsResult.rows.map((row) => decorateEmployeeCode(table, row)),
    total: Number(countResult.rows[0]?.count ?? 0),
  };
}

export async function listDesignationRowsByDepartment(departmentId: string, limit = 500, offset = 0) {
  const table = getTable("designation_master");
  const orderColumn = getOrderColumn(table);
  const rowsResult = await pool.query(
    `select * from ${quoteIdentifier(table.table_name)} where ${quoteIdentifier("department_id")} = $1 order by ${quoteIdentifier(orderColumn)} desc limit $2 offset $3`,
    [departmentId, limit, offset],
  );
  const countResult = await pool.query(
    `select count(*)::int as count from ${quoteIdentifier(table.table_name)} where ${quoteIdentifier("department_id")} = $1`,
    [departmentId],
  );

  return {
    table,
    rows: rowsResult.rows,
    total: Number(countResult.rows[0]?.count ?? 0),
  };
}

export async function listShiftPolicyRowsByLocation(locationId: string, limit = 500, offset = 0) {
  const table = getTable("shift_policy_master");
  const orderColumn = getOrderColumn(table);
  const rowsResult = await pool.query(
    `select * from ${quoteIdentifier(table.table_name)} where ${quoteIdentifier("location_id")} = $1 order by ${quoteIdentifier(orderColumn)} desc limit $2 offset $3`,
    [locationId, limit, offset],
  );
  const countResult = await pool.query(
    `select count(*)::int as count from ${quoteIdentifier(table.table_name)} where ${quoteIdentifier("location_id")} = $1`,
    [locationId],
  );

  return {
    table,
    rows: rowsResult.rows,
    total: Number(countResult.rows[0]?.count ?? 0),
  };
}

export async function getTableRow(tableName: string, recordId: string) {
  const table = getTable(tableName);
  const result = await pool.query(
    `select * from ${quoteIdentifier(table.table_name)} where ${quoteIdentifier(getPrimaryKey(table))} = $1`,
    [recordId],
  );

  return result.rows[0] ? decorateEmployeeCode(table, result.rows[0]) : null;
}

export async function getTableOverview() {
  const counts = await Promise.all(
    allTables.map(async (table) => {
      const result = await pool.query(`select count(*)::int as count from ${quoteIdentifier(table.table_name)}`);
      return {
        table_name: table.table_name,
        count: Number(result.rows[0]?.count ?? 0),
      };
    }),
  );

  return counts;
}

async function ensureHqExists(tableName: string, entityRole: unknown) {
  if (tableName !== "parent_entity") return;
  const role = String(entityRole ?? "").trim().toLowerCase();
  if (role === "hq") return;

  const result = await pool.query(`SELECT 1 FROM parent_entity WHERE entity_role = 'hq' LIMIT 1`);
  if (result.rowCount === 0) {
    throw new Error("An HQ entity must be created first before adding other entities.");
  }
}

async function ensureNotLastHq(tableName: string, recordId: string, newRole?: string) {
  if (tableName !== "parent_entity") return;

  const roleResult = await pool.query(
    `SELECT entity_role FROM parent_entity WHERE ${quoteIdentifier(getTable(tableName).primary_key[0])} = $1`,
    [recordId],
  );
  const currentRole = String(roleResult.rows[0]?.entity_role ?? "").trim().toLowerCase();
  const targetRole = newRole ? String(newRole).trim().toLowerCase() : currentRole;

  if (targetRole === "hq") return;

  const hqCount = await pool.query(`SELECT count(*)::int AS cnt FROM parent_entity WHERE entity_role = 'hq'`);
  const total = hqCount.rows[0]?.cnt ?? 0;

  if (currentRole === "hq" && total <= 1) {
    throw new Error("Cannot remove the last HQ entity. Create another HQ first.");
  }
}

export async function createTableRow(tableName: string, input: RecordPayload) {
  const table = getTable(tableName);
  const payload = normalizeRecordInput(table, input);
  const columns = Object.keys(payload);

  if (columns.length === 0) {
    throw new Error(`No valid values were provided for ${table.table_name}`);
  }

  await ensureHqExists(tableName, payload.entity_role);

  const values = columns.map((column) => payload[column]);
  const placeholders = columns.map((_, index) => `$${index + 1}`).join(", ");
  const columnList = columns.map((column) => quoteIdentifier(column)).join(", ");
  const result = await pool.query(
    `insert into ${quoteIdentifier(table.table_name)} (${columnList}) values (${placeholders}) returning *`,
    values,
  );

  return decorateEmployeeCode(table, result.rows[0]);
}

export async function updateTableRow(tableName: string, recordId: string, input: RecordPayload) {
  const table = getTable(tableName);
  const payload = normalizeRecordInput(table, input);
  const columns = Object.keys(payload);

  if (columns.length === 0) {
    throw new Error(`No valid values were provided for ${table.table_name}`);
  }

  if (payload.entity_role !== undefined) {
    await ensureNotLastHq(tableName, recordId, String(payload.entity_role));
  }

  const assignments = columns.map((column, index) => `${quoteIdentifier(column)} = $${index + 1}`);
  const values = columns.map((column) => payload[column]);
  const where = buildWhereClause(table, recordId, columns.length);

  const result = await pool.query(
    `update ${quoteIdentifier(table.table_name)} set ${assignments.join(", ")} where ${where.where} returning *`,
    [...values, ...where.values],
  );

  return result.rows[0] ? decorateEmployeeCode(table, result.rows[0]) : null;
}

export async function deleteTableRow(tableName: string, recordId: string) {
  await ensureNotLastHq(tableName, recordId);

  const client = await pool.connect();
  const visited = new Set<string>();
  const touchedTables = new Set<string>();

  try {
    await client.query("begin");
    const row = await deleteTableRowWithDependents(client, tableName, recordId, visited, touchedTables);

    for (const touchedTable of touchedTables) {
      await resetTableSequence(client, touchedTable);
    }

    await client.query("commit");
    return row;
  } catch (error) {
    await client.query("rollback");
    throw error;
  } finally {
    client.release();
  }
}

export function getTableDetails(tableName: string) {
  const table = getTable(tableName);
  return {
    table,
    label: formatLabel(table.table_name),
    primaryKey: getPrimaryKey(table),
  };
}

export function isSupportedTable(tableName: string) {
  return tableName in tableLookup;
}

export function getRelatedTables(tableName: string) {
  const table = getTable(tableName);
  return table.foreign_keys.map((foreignKey) => ({
    ...foreignKey,
    referenced: tableLookup[foreignKey.references_table],
  }));
}

export async function writeAuditLog(
  tableName: string,
  action: string,
  oldData: Record<string, unknown> | null,
  newData: Record<string, unknown> | null,
) {
  const employeeId = String(
    (newData?.employee_id ?? oldData?.employee_id ?? "") as string,
  ).trim();
  if (!employeeId) return;
  await pool.query(
    `insert into employee_audit_log (employee_id, action, old_data, new_data, changed_at) values ($1, $2, $3::jsonb, $4::jsonb, now())`,
    [
      employeeId,
      action,
      oldData ? JSON.stringify(oldData) : null,
      newData ? JSON.stringify(newData) : null,
    ],
  );
}

export async function listEmployeeLookupRows(purpose: string, limit = 500, offset = 0, locationId?: string) {
  const table = getTable("employee_master");
  const orderColumn = table.columns.some((column) => column.column === "employee_code")
    ? "employee_code"
    : getOrderColumn(table);

  let whereClause = `coalesce(${quoteIdentifier("status")}, '') ilike 'active%'`;
  const params: unknown[] = [];

  if (purpose === "reporting_manager") {
    whereClause += ` and ${quoteIdentifier("is_reporting_manager")} = true`;
  }

  if (purpose === "keyholder") {
    whereClause += ` and exists (select 1 from ${quoteIdentifier("designation_master")} dm where dm.${quoteIdentifier("designation_id")} = ${quoteIdentifier("employee_master")}.${quoteIdentifier("designation_id")} and dm.${quoteIdentifier("is_keyholder_eligible")} = true)`;
  }

  if (locationId) {
    whereClause += ` and ${quoteIdentifier("location_id")} = $${params.length + 1}`;
    params.push(locationId);
  }

  params.push(limit, offset);

  const rowsResult = await pool.query(
    `select * from ${quoteIdentifier(table.table_name)} where ${whereClause} order by ${quoteIdentifier(orderColumn)} asc limit $${params.length - 1} offset $${params.length}`,
    params,
  );

  const countParams = params.slice(0, -2);
  const countResult = await pool.query(
    `select count(*)::int as count from ${quoteIdentifier(table.table_name)} where ${whereClause}`,
    countParams,
  );

  return {
    table,
    rows: rowsResult.rows,
    total: Number(countResult.rows[0]?.count ?? 0),
  };
}
