-- Migration: employee address table with present/permanent address and same-address sync

CREATE TABLE IF NOT EXISTS employee_address (
  employee_address_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id integer,
  same_address boolean DEFAULT false,
  present_address_line1 text,
  present_address_line2 text,
  present_country text,
  present_state text,
  present_city text,
  present_pincode text,
  permanent_address_line1 text,
  permanent_address_line2 text,
  permanent_country text,
  permanent_state text,
  permanent_city text,
  permanent_pincode text,
  status text
);

-- Ensure all columns exist even if the table already existed without some of them
ALTER TABLE employee_address ADD COLUMN IF NOT EXISTS same_address boolean DEFAULT false;
ALTER TABLE employee_address ADD COLUMN IF NOT EXISTS present_address_line1 text;
ALTER TABLE employee_address ADD COLUMN IF NOT EXISTS present_address_line2 text;
ALTER TABLE employee_address ADD COLUMN IF NOT EXISTS present_country text;
ALTER TABLE employee_address ADD COLUMN IF NOT EXISTS present_state text;
ALTER TABLE employee_address ADD COLUMN IF NOT EXISTS present_city text;
ALTER TABLE employee_address ADD COLUMN IF NOT EXISTS present_pincode text;
ALTER TABLE employee_address ADD COLUMN IF NOT EXISTS permanent_address_line1 text;
ALTER TABLE employee_address ADD COLUMN IF NOT EXISTS permanent_address_line2 text;
ALTER TABLE employee_address ADD COLUMN IF NOT EXISTS permanent_country text;
ALTER TABLE employee_address ADD COLUMN IF NOT EXISTS permanent_state text;
ALTER TABLE employee_address ADD COLUMN IF NOT EXISTS permanent_city text;
ALTER TABLE employee_address ADD COLUMN IF NOT EXISTS permanent_pincode text;
ALTER TABLE employee_address ADD COLUMN IF NOT EXISTS status text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE table_schema = 'public'
      AND table_name = 'employee_address'
      AND constraint_name = 'employee_address_employee_id_fkey'
  ) THEN
    ALTER TABLE employee_address
      ADD CONSTRAINT employee_address_employee_id_fkey
      FOREIGN KEY (employee_id) REFERENCES employee_master(employee_id);
  END IF;
END;
$$;

CREATE UNIQUE INDEX IF NOT EXISTS employee_address_employee_id_ux
  ON employee_address (employee_id)
  WHERE employee_id IS NOT NULL;

CREATE OR REPLACE FUNCTION sync_employee_address_same_fields()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF COALESCE(NEW.same_address, false) THEN
    NEW.permanent_address_line1 := NEW.present_address_line1;
    NEW.permanent_address_line2 := NEW.present_address_line2;
    NEW.permanent_country := NEW.present_country;
    NEW.permanent_state := NEW.present_state;
    NEW.permanent_city := NEW.present_city;
    NEW.permanent_pincode := NEW.present_pincode;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS employee_address_same_fields_trg ON employee_address;

CREATE TRIGGER employee_address_same_fields_trg
BEFORE INSERT OR UPDATE OF same_address, present_address_line1, present_address_line2, present_country, present_state, present_city, present_pincode
ON employee_address
FOR EACH ROW
EXECUTE FUNCTION sync_employee_address_same_fields();